-- ROLLBACK du dégraissage du 2026-08-25.
--
-- Rend les STRUCTURES telles qu'elles étaient (DDL relevé sur l'état live avant
-- suppression). Les DONNÉES ne reviennent pas d'ici : elles vivent en local et
-- se re-poussent avec `ops/remonter-local.py`.
--
-- ⚠ Rejouer ceci ramène ~578 Mo sur un quota gratuit de 500 Mo. À ne faire que
-- si la décision de posture est annulée, pas par réflexe.
--
-- ⚠ Il faut AUSSI défaire le code, sinon rien ne remplira ces objets :
--   - store/base.py       : remettre "description", "page_text" dans COLONNES_LISTING
--   - supabase_store.py   : rétablir l'appel à _set_amenities et renommer
--                           _record_cohort_snapshots_ancien en record_cohort_snapshots

begin;

alter table listings add column if not exists page_text bytea;
alter table listings add column if not exists description text;

create table if not exists listing_amenities (
  id bigint generated by default as identity primary key,
  listing_id text not null,
  name text not null
);
create index if not exists idx_amenities_listing on public.listing_amenities using btree (listing_id);

create table if not exists cohort_snapshots (
  id bigint generated by default as identity primary key,
  taken_at timestamp with time zone not null default now(),
  unit_key text not null,
  condo_name text,
  khet text,
  deal_type text,
  bedrooms integer,
  area_bucket integer,
  active_count integer not null,
  median_price numeric,
  min_price numeric,
  max_price numeric
);
create index if not exists idx_cohort_snap_key on public.cohort_snapshots using btree (unit_key, taken_at desc);
create index if not exists idx_cohort_snap_date on public.cohort_snapshots using btree (taken_at desc);

-- security_invoker : sans lui, `create view` fait une vue SECURITY DEFINER
-- appartenant à `postgres` (rolbypassrls), ce qui rouvre la faille fermée le
-- 2026-08-20. Ne jamais retirer cette clause.
create or replace view cohort_tension with (security_invoker = true) as
 with derniers as (
   select unit_key, condo_name, khet, deal_type, bedrooms, area_bucket,
          active_count, median_price, taken_at,
          row_number() over (partition by unit_key order by taken_at desc) as rn
     from cohort_snapshots
 )
 select a.unit_key, a.condo_name, a.khet, a.deal_type, a.bedrooms, a.area_bucket,
        a.active_count as stock_actuel, b.active_count as stock_precedent,
        a.active_count - b.active_count as variation, a.median_price, a.taken_at
   from derniers a
   join derniers b on b.unit_key = a.unit_key and b.rn = 2
  where a.rn = 1;

create or replace view description_couverture with (security_invoker = true) as
 select source, count(*) as annonces, count(description) as avec_description,
        round(100.0 * count(description)::numeric / nullif(count(*), 0)::numeric, 1) as pct,
        round(avg(length(description))) as longueur_moyenne
   from listings
  where status = 'active'::text
  group by source
  order by (count(*)) desc;

commit;
